camunda.bpm:
  admin-user:
   id: demo
   password: demo
   firstName: Demo
  filter:
   create: All tasks
server:
  port: 8081

spring:
  cloud:
    function:
      definition: producer
    stream:
      kafka:
        bindings:
          saveToAccountStorage-in-0:
            destination: saveBankAccountTopic
        binder:
          brokers: localhost:9092
